#!/bin/bash
CUR=$(dirname $(readlink -f $0))

case "$1" in
    "-d")
        docker-compose -f $CUR/../docker-compose.yml up dev -d --remove-orphans
        ;;
    *)
        docker-compose -f $CUR/../docker-compose.yml up dev --remove-orphans
        ;;
esac